// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UpdateSpuRequest struct {
	GoodsName   string  `json:"goodsName"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type UpdateSpuResponse struct {
	GoodsName   string  `json:"goodsName"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}
