// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UpdateSpuRequest struct {
	Id          uint    `json:"id"`
	GoodsName   string  `json:"goodsName"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type UpdateSpuResponse struct {
	GoodsName   string  `json:"goodsName"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type CreateSpuRequest struct {
	GoodsName   string  `json:"goodsName"` //商品名
	Category    string  `json:"category"`  //分类
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type CreateSpuResponse struct {
	Message string `json:"message"`
}

type DeleteSpuRequest struct {
	Id uint `json:"id"`
}

type SearchSpuRequest struct {
	Id          uint    `json:"id"`
	GoodsName   string  `json:"goodsName"` //商品名
	Category    string  `json:"category"`  //分类
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type SearchSpuResponse struct {
	Res []SearchSpuRequest `json:"res"`
}
